---
- name: install chrome stable - download linux_signing_key.pub
  get_url:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    dest: "/home/{{ username }}/setup/linux_signing_key.pub"
    mode: 0440

- name: Change permissions for linux_signing_key.pub
  file:
    path: "/home/{{ username }}/setup/linux_signing_key.pub"
    user: "{{ username }}"
    mode: 0755
    group: "{{ username }}"
  sudo: yes

- name: install chrome stable - add linux_signing_key.pub to keys
  command: "apt-key add /home/{{ username }}/setup/linux_signing_key.pub"
  sudo: yes

- name: install chrome stable - add to google.list
  lineinfile:
    dest: /etc/apt/sources.list.d/google.list
    line: deb http://dl.google.com/linux/chrome/deb/ stable main
    create: yes
  sudo: yes

- name: install chrome stable
  apt:
    name: google-chrome-stable
    update_cache: yes
    force: yes
  sudo: yes
